name: Build and Release

on:
  push:
    tags:
      - 'v*'
    branches: [ "master" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: docker
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    - name: Build binary
      run: |
        mkdir -p dist/
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o proxmox-dns-server-linux-amd64 .
        cp proxmox-dns-server-linux-amd64 dist/
    - name: Upload binary to release
      uses: actions/forgejo-release@v2.7.1
      with:
        direction: upload
        url: ${{ inputs.forgejo }}
        repo: ${{ inputs.to-owner }}/${{ inputs.repo }}
        release-notes: "Uploaded from Forgejo"
        token: ${{ inputs.token }}
        release-dir: dist/